# - - - - - - - - - - - - - - #
# EasterEggHunt Configuration #
# - - - - - - - - - - - - - - #
# --- eggHuntEnabled ---
# boolean. when set to false, plugin will do nothing.
# --- apiEndpoint ---
# The score tracking API endpoint without a trailing slash
# --- apiKey ---
# API key for score tracking for this server
# --- defaultHuntType ---
# The default hunt type to use if it is not specified for a hunt, or if there is a spelling error.
# If this value is invalid, 'easter' will be forced. Allowed values are 'halloween', 'christmas' and 'easter'.
# Hunt type value must be in LOWER-CASE letters.
# --- hunts ---
# WorldGuard regions where egg hunts are taking place. Use LOWER-CASE letters in world and region names. Timings are in seconds.
# For example,
#   hunts:
#     world_name:
#       region_name:
#         enabled: true
#         type: 'halloween|christmas|easter'
#         friendly_name: 'Region Name'
#         delay: 8

eggHuntEnabled: false
apiEndpoint: ''
apiKey: ''
defaultHuntType: 'easter'
hunts: []